repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
      exclude: ^templates/templated_email/compiled/
    - id: end-of-file-fixer
      exclude: ^templates/templated_email/compiled/
    - id: flake8
      additional_dependencies:
        - flake8-docstrings

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
      # args: [--exclude=tests/.*\.py]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
    - id: isort
      additional_dependencies:
        - toml

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      language: system
      # for gui tool to work, we'd better make sure POETRY_SHELL exposed
      # MacOS, $ `open -a /Applications/Sourcetree.app`
      # 1. copy all the dependencies to `additional_dependencies`
      # 2. expose `poetry` to PATH and use `language: system`
      entry: poetry run mypy
      types: [python]
      exclude: tests/
