[tool.poetry]
name = "cishe"
version = "0.1.0"
description = "Client Info System for Hello Education"
authors = ["Ace <ace.jl.han@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
arrow = "^0.15.6"
djangorestframework = "^3.11.0"
requests = "^2.23.0"
openpyxl = "^3.0.3"
pymysql = {version = "^0.9.3", extras = ["rsa"]}
django-environ = "^0.4.5"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
flake8-docstrings = "^1.5.0"
darglint = "^1.4.1"
isort = "^4.3.21"
seed-isort-config = "^2.2.0"
pre-commit = "^2.5.1"
pytest = "^5.4.3"
pytest-django = "^3.9.0"
pytest-cov = "^2.9.0"
pytest-mock = "^3.1.1"
xdoctest = "^0.12.0"
tox = "^3.15.2"
mypy = "^0.780"
ptvsd = "^4.3.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
