version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run: 
          command: pip install -r requirements_dev.txt
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build-and-test
