version: 2.1

orbs:
  poetry: thomasborgen/python-poetry-orb@1.0.0

jobs:
  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - poetry/install:
          args: '--no-root'
      - poetry/export:
          args: '--dev -f requirements.txt -o requirements.txt'
      - poetry/shell:
          args: tox

workflows:
  main:
    jobs:
      - test
