# Generated by Django 3.1.1 on 2020-12-11 03:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_num2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "parent_phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("parent_type", models.CharField(blank=True, max_length=8)),
                ("university", models.CharField(max_length=32)),
                ("department", models.CharField(blank=True, max_length=32)),
                ("major", models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_num", models.CharField(blank=True, max_length=16)),
                ("contract_type", models.CharField(max_length=8)),
                ("source", models.CharField(blank=True, max_length=8)),
                ("signing_date", models.DateTimeField()),
                ("signing_branch", models.CharField(blank=True, max_length=4)),
                ("probation_until", models.DateTimeField()),
                ("total_amount", models.PositiveIntegerField()),
                ("referrer", models.CharField(blank=True, max_length=32)),
                ("supplementary_agreement", models.TextField(blank=True)),
                (
                    "sale_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contract.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_semester", models.CharField(max_length=4)),
                ("retention_statement", models.CharField(blank=True, max_length=32)),
                ("target_country_code", models.CharField(max_length=32)),
                ("target_subject", models.CharField(max_length=4)),
                ("target_degree", models.CharField(max_length=4)),
                ("target_major", models.CharField(max_length=32)),
                ("team", models.CharField(max_length=4)),
                ("workload", models.FloatField()),
                ("status", models.CharField(blank=True, max_length=32)),
                ("start_date", models.DateTimeField()),
                ("remark", models.TextField(blank=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contract.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TakeOver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateTimeField()),
                ("remark", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contract.contract",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("counselor", "contract")},
            },
        ),
    ]
