# Generated by Django 3.1.1 on 2020-10-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="total_amount_remark",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="takeover",
            name="remark",
        ),
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contract.customer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="serviceinfo",
            name="remark",
            field=models.TextField(blank=True),
        ),
    ]
