name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
            - name: Set Poetry config
            run: |
              poetry config settings.virtualenvs.in-project false
              poetry config settings.virtualenvs.path ~/.virtualenvs
    
      - name: Install Dependencies
        run: poetry install --no-root
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: cishe.settings
        #   SECRETS_FILE: .confidential/ci.json
        run: poetry run pytest --cov=. --cov-report=term-missing --junitxml=junit/test-results.xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: junit/test-results.xml
          flags: overall
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true

      - uses: actions/upload-artifact@v1
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}